name: real_estate_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.19.0

  #Database
  floor: any

  #make request to api
  retrofit: '>=4.0.0 <5.0.0'

  #Hooks
  flutter_hooks: ^0.20.5

  #chached image 
  cached_network_image: ^3.2.0

  flutter_svg: ^2.1.0
  provider: ^6.1.0
  percent_indicator: ^4.2.5

  font_awesome_flutter: 10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.11


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf

        # -asset: assets/fonts/lato/Lato-Black.ttf
        # -asset: assets/fonts/lato/Lato-Blacktalic.ttf
        # -asset: assets/fonts/lato/Lato-Bold.ttf
        # -asset: assets/fonts/lato/Lato-Italic.ttf
        # -asset: assets/fonts/lato/Lato-Light.ttf
        # -asset: assets/fonts/lato/Lato-LightItalic.ttf
       
        # -asset: assets/fonts/lato/Lato-Thin.ttf
        # -asset: assets/fonts/lato/Lato-ThinItalic.ttf


